services:
  parfumo:
    build: .
    image: parfumo_scraper:latest
    container_name: parfumo_scraper
    volumes:
      - ./parfumo_dumps:/app/parfumo_dumps
      - .:/app:ro
      - scrapy_cache_vol:/app/.scrapy
    environment:
      - INSTALL_PLAYWRIGHT_BROWSERS=0
    command: ["scrapy", "crawl", "parfumo_spider", "-a", "max_brand_pages=1", "-a", "dump_html=False"]
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M

volumes:
  scrapy_cache_vol:
